git:
  submodules: false
language: cpp
env:
- CXX=/usr/bin/clang++-3.4 CC=/usr/bin/clang-3.4
- CXX=/usr/bin/clang++-3.5 CC=/usr/bin/clang-3.5
- CXX=/usr/bin/clang++-3.7 CC=/usr/bin/clang-3.7

before_install:
- sudo add-apt-repository -y ppa:mapnik/boost-backports-1-54
- sudo add-apt-repository -y ppa:kalakris/eigen
- sudo add-apt-repository -y ppa:feelpp/ppa
- sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
- sudo apt-add-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
- sudo apt-add-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
- sudo apt-get update
- apt-cache search clang
- sudo apt-get install clang-3.5
- sudo apt-get install -qq libboost1.54-all-dev mpi-default-dev mpi-default-bin libeigen3-dev
  libcln-dev petsc-dev libxml2-dev gmsh bison flex doxygen doxygen-latex transfig
  imagemagick libtbb-dev libann-dev libglpk-dev
- sudo apt-get install libfeel++-dev
install:
- mkdir opt && cd opt && ../configure -r --cxxflags="-O2 -DNDEBUG"
script:
- make
branches:
  only:
  - master
  - develop
cache:
- apt
notifications:
  email:
    recipients:
    - feelpp-devel@feelpp.org
    on_success: change
